language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements/requirements-test.txt"
# command to run tests
script:
  - "flake8 hoft setup.py"
  - "pep8 hoft setup.py"
  - "pylint -E hoft setup.py"
  - "nosetests --with-coverage --cover-erase --cover-package=hoft --cover-html"

after_success:
  - "coveralls"
